fix flake8 lint issues
./judge/contest_format/ioi.py:4:1: F811 redefinition of unused 'gettext_lazy' from line 3
./judge/management/commands/generate_report.py:76:48: Q000 Double quotes found but single quotes preferred
./judge/management/commands/generate_report.py:93:33: Q000 Double quotes found but single quotes preferred